# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse200153GetObsrestoreDatamoverPerfresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'usages_count': 'int',
        'usages': 'list[InlineResponse200153GetObsrestoreDatamoverPerfresponseUsages]'
    }

    attribute_map = {
        'status': 'status',
        'usages_count': 'usages-count',
        'usages': 'usages'
    }

    def __init__(self, status=None, usages_count=None, usages=None, _configuration=None):  # noqa: E501
        """InlineResponse200153GetObsrestoreDatamoverPerfresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._usages_count = None
        self._usages = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if usages_count is not None:
            self.usages_count = usages_count
        if usages is not None:
            self.usages = usages

    @property
    def status(self):
        """Gets the status of this InlineResponse200153GetObsrestoreDatamoverPerfresponse.  # noqa: E501


        :return: The status of this InlineResponse200153GetObsrestoreDatamoverPerfresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200153GetObsrestoreDatamoverPerfresponse.


        :param status: The status of this InlineResponse200153GetObsrestoreDatamoverPerfresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def usages_count(self):
        """Gets the usages_count of this InlineResponse200153GetObsrestoreDatamoverPerfresponse.  # noqa: E501


        :return: The usages_count of this InlineResponse200153GetObsrestoreDatamoverPerfresponse.  # noqa: E501
        :rtype: int
        """
        return self._usages_count

    @usages_count.setter
    def usages_count(self, usages_count):
        """Sets the usages_count of this InlineResponse200153GetObsrestoreDatamoverPerfresponse.


        :param usages_count: The usages_count of this InlineResponse200153GetObsrestoreDatamoverPerfresponse.  # noqa: E501
        :type: int
        """

        self._usages_count = usages_count

    @property
    def usages(self):
        """Gets the usages of this InlineResponse200153GetObsrestoreDatamoverPerfresponse.  # noqa: E501


        :return: The usages of this InlineResponse200153GetObsrestoreDatamoverPerfresponse.  # noqa: E501
        :rtype: list[InlineResponse200153GetObsrestoreDatamoverPerfresponseUsages]
        """
        return self._usages

    @usages.setter
    def usages(self, usages):
        """Sets the usages of this InlineResponse200153GetObsrestoreDatamoverPerfresponse.


        :param usages: The usages of this InlineResponse200153GetObsrestoreDatamoverPerfresponse.  # noqa: E501
        :type: list[InlineResponse200153GetObsrestoreDatamoverPerfresponseUsages]
        """

        self._usages = usages

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200153GetObsrestoreDatamoverPerfresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200153GetObsrestoreDatamoverPerfresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200153GetObsrestoreDatamoverPerfresponse):
            return True

        return self.to_dict() != other.to_dict()
