# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse200120Showremotecgsresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'cgs_count': 'int',
        'cgs': 'list[InlineResponse200120ShowremotecgsresponseCgs]'
    }

    attribute_map = {
        'status': 'status',
        'cgs_count': 'cgs-count',
        'cgs': 'cgs'
    }

    def __init__(self, status=None, cgs_count=None, cgs=None, _configuration=None):  # noqa: E501
        """InlineResponse200120Showremotecgsresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._cgs_count = None
        self._cgs = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if cgs_count is not None:
            self.cgs_count = cgs_count
        if cgs is not None:
            self.cgs = cgs

    @property
    def status(self):
        """Gets the status of this InlineResponse200120Showremotecgsresponse.  # noqa: E501


        :return: The status of this InlineResponse200120Showremotecgsresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200120Showremotecgsresponse.


        :param status: The status of this InlineResponse200120Showremotecgsresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def cgs_count(self):
        """Gets the cgs_count of this InlineResponse200120Showremotecgsresponse.  # noqa: E501


        :return: The cgs_count of this InlineResponse200120Showremotecgsresponse.  # noqa: E501
        :rtype: int
        """
        return self._cgs_count

    @cgs_count.setter
    def cgs_count(self, cgs_count):
        """Sets the cgs_count of this InlineResponse200120Showremotecgsresponse.


        :param cgs_count: The cgs_count of this InlineResponse200120Showremotecgsresponse.  # noqa: E501
        :type: int
        """

        self._cgs_count = cgs_count

    @property
    def cgs(self):
        """Gets the cgs of this InlineResponse200120Showremotecgsresponse.  # noqa: E501


        :return: The cgs of this InlineResponse200120Showremotecgsresponse.  # noqa: E501
        :rtype: list[InlineResponse200120ShowremotecgsresponseCgs]
        """
        return self._cgs

    @cgs.setter
    def cgs(self, cgs):
        """Sets the cgs of this InlineResponse200120Showremotecgsresponse.


        :param cgs: The cgs of this InlineResponse200120Showremotecgsresponse.  # noqa: E501
        :type: list[InlineResponse200120ShowremotecgsresponseCgs]
        """

        self._cgs = cgs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200120Showremotecgsresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200120Showremotecgsresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200120Showremotecgsresponse):
            return True

        return self.to_dict() != other.to_dict()
