# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse200106Showremotevpsasresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'remote_vpsas_count': 'int',
        'remote_vpsas': 'list[InlineResponse200106ShowremotevpsasresponseRemotevpsas]'
    }

    attribute_map = {
        'status': 'status',
        'remote_vpsas_count': 'remote-vpsas-count',
        'remote_vpsas': 'remote-vpsas'
    }

    def __init__(self, status=None, remote_vpsas_count=None, remote_vpsas=None, _configuration=None):  # noqa: E501
        """InlineResponse200106Showremotevpsasresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._remote_vpsas_count = None
        self._remote_vpsas = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if remote_vpsas_count is not None:
            self.remote_vpsas_count = remote_vpsas_count
        if remote_vpsas is not None:
            self.remote_vpsas = remote_vpsas

    @property
    def status(self):
        """Gets the status of this InlineResponse200106Showremotevpsasresponse.  # noqa: E501


        :return: The status of this InlineResponse200106Showremotevpsasresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200106Showremotevpsasresponse.


        :param status: The status of this InlineResponse200106Showremotevpsasresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def remote_vpsas_count(self):
        """Gets the remote_vpsas_count of this InlineResponse200106Showremotevpsasresponse.  # noqa: E501


        :return: The remote_vpsas_count of this InlineResponse200106Showremotevpsasresponse.  # noqa: E501
        :rtype: int
        """
        return self._remote_vpsas_count

    @remote_vpsas_count.setter
    def remote_vpsas_count(self, remote_vpsas_count):
        """Sets the remote_vpsas_count of this InlineResponse200106Showremotevpsasresponse.


        :param remote_vpsas_count: The remote_vpsas_count of this InlineResponse200106Showremotevpsasresponse.  # noqa: E501
        :type: int
        """

        self._remote_vpsas_count = remote_vpsas_count

    @property
    def remote_vpsas(self):
        """Gets the remote_vpsas of this InlineResponse200106Showremotevpsasresponse.  # noqa: E501


        :return: The remote_vpsas of this InlineResponse200106Showremotevpsasresponse.  # noqa: E501
        :rtype: list[InlineResponse200106ShowremotevpsasresponseRemotevpsas]
        """
        return self._remote_vpsas

    @remote_vpsas.setter
    def remote_vpsas(self, remote_vpsas):
        """Sets the remote_vpsas of this InlineResponse200106Showremotevpsasresponse.


        :param remote_vpsas: The remote_vpsas of this InlineResponse200106Showremotevpsasresponse.  # noqa: E501
        :type: list[InlineResponse200106ShowremotevpsasresponseRemotevpsas]
        """

        self._remote_vpsas = remote_vpsas

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200106Showremotevpsasresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200106Showremotevpsasresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200106Showremotevpsasresponse):
            return True

        return self.to_dict() != other.to_dict()
