# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse200112Getdstjobforresumeresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'sugested_jobs_count': 'int',
        'sugested_jobs': 'list[InlineResponse200112GetdstjobforresumeresponseSugestedjobs]'
    }

    attribute_map = {
        'status': 'status',
        'sugested_jobs_count': 'sugested-jobs-count',
        'sugested_jobs': 'sugested-jobs'
    }

    def __init__(self, status=None, sugested_jobs_count=None, sugested_jobs=None, _configuration=None):  # noqa: E501
        """InlineResponse200112Getdstjobforresumeresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._sugested_jobs_count = None
        self._sugested_jobs = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if sugested_jobs_count is not None:
            self.sugested_jobs_count = sugested_jobs_count
        if sugested_jobs is not None:
            self.sugested_jobs = sugested_jobs

    @property
    def status(self):
        """Gets the status of this InlineResponse200112Getdstjobforresumeresponse.  # noqa: E501


        :return: The status of this InlineResponse200112Getdstjobforresumeresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200112Getdstjobforresumeresponse.


        :param status: The status of this InlineResponse200112Getdstjobforresumeresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def sugested_jobs_count(self):
        """Gets the sugested_jobs_count of this InlineResponse200112Getdstjobforresumeresponse.  # noqa: E501


        :return: The sugested_jobs_count of this InlineResponse200112Getdstjobforresumeresponse.  # noqa: E501
        :rtype: int
        """
        return self._sugested_jobs_count

    @sugested_jobs_count.setter
    def sugested_jobs_count(self, sugested_jobs_count):
        """Sets the sugested_jobs_count of this InlineResponse200112Getdstjobforresumeresponse.


        :param sugested_jobs_count: The sugested_jobs_count of this InlineResponse200112Getdstjobforresumeresponse.  # noqa: E501
        :type: int
        """

        self._sugested_jobs_count = sugested_jobs_count

    @property
    def sugested_jobs(self):
        """Gets the sugested_jobs of this InlineResponse200112Getdstjobforresumeresponse.  # noqa: E501


        :return: The sugested_jobs of this InlineResponse200112Getdstjobforresumeresponse.  # noqa: E501
        :rtype: list[InlineResponse200112GetdstjobforresumeresponseSugestedjobs]
        """
        return self._sugested_jobs

    @sugested_jobs.setter
    def sugested_jobs(self, sugested_jobs):
        """Sets the sugested_jobs of this InlineResponse200112Getdstjobforresumeresponse.


        :param sugested_jobs: The sugested_jobs of this InlineResponse200112Getdstjobforresumeresponse.  # noqa: E501
        :type: list[InlineResponse200112GetdstjobforresumeresponseSugestedjobs]
        """

        self._sugested_jobs = sugested_jobs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200112Getdstjobforresumeresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200112Getdstjobforresumeresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200112Getdstjobforresumeresponse):
            return True

        return self.to_dict() != other.to_dict()
