# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse20057Shownasusersresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'users_count': 'int',
        'users': 'list[InlineResponse20057ShownasusersresponseUsers]'
    }

    attribute_map = {
        'status': 'status',
        'users_count': 'users-count',
        'users': 'users'
    }

    def __init__(self, status=None, users_count=None, users=None, _configuration=None):  # noqa: E501
        """InlineResponse20057Shownasusersresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._users_count = None
        self._users = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if users_count is not None:
            self.users_count = users_count
        if users is not None:
            self.users = users

    @property
    def status(self):
        """Gets the status of this InlineResponse20057Shownasusersresponse.  # noqa: E501


        :return: The status of this InlineResponse20057Shownasusersresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20057Shownasusersresponse.


        :param status: The status of this InlineResponse20057Shownasusersresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def users_count(self):
        """Gets the users_count of this InlineResponse20057Shownasusersresponse.  # noqa: E501


        :return: The users_count of this InlineResponse20057Shownasusersresponse.  # noqa: E501
        :rtype: int
        """
        return self._users_count

    @users_count.setter
    def users_count(self, users_count):
        """Sets the users_count of this InlineResponse20057Shownasusersresponse.


        :param users_count: The users_count of this InlineResponse20057Shownasusersresponse.  # noqa: E501
        :type: int
        """

        self._users_count = users_count

    @property
    def users(self):
        """Gets the users of this InlineResponse20057Shownasusersresponse.  # noqa: E501


        :return: The users of this InlineResponse20057Shownasusersresponse.  # noqa: E501
        :rtype: list[InlineResponse20057ShownasusersresponseUsers]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this InlineResponse20057Shownasusersresponse.


        :param users: The users of this InlineResponse20057Shownasusersresponse.  # noqa: E501
        :type: list[InlineResponse20057ShownasusersresponseUsers]
        """

        self._users = users

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20057Shownasusersresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20057Shownasusersresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20057Shownasusersresponse):
            return True

        return self.to_dict() != other.to_dict()
