# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse200239(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'create_migration_job_response': 'InlineResponse200239Createmigrationjobresponse'
    }

    attribute_map = {
        'create_migration_job_response': 'create-migration-job-response'
    }

    def __init__(self, create_migration_job_response=None, _configuration=None):  # noqa: E501
        """InlineResponse200239 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._create_migration_job_response = None
        self.discriminator = None

        if create_migration_job_response is not None:
            self.create_migration_job_response = create_migration_job_response

    @property
    def create_migration_job_response(self):
        """Gets the create_migration_job_response of this InlineResponse200239.  # noqa: E501


        :return: The create_migration_job_response of this InlineResponse200239.  # noqa: E501
        :rtype: InlineResponse200239Createmigrationjobresponse
        """
        return self._create_migration_job_response

    @create_migration_job_response.setter
    def create_migration_job_response(self, create_migration_job_response):
        """Sets the create_migration_job_response of this InlineResponse200239.


        :param create_migration_job_response: The create_migration_job_response of this InlineResponse200239.  # noqa: E501
        :type: InlineResponse200239Createmigrationjobresponse
        """

        self._create_migration_job_response = create_migration_job_response

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200239, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200239):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200239):
            return True

        return self.to_dict() != other.to_dict()
