# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse20071Showpoolsresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'pools_count': 'int',
        'pools': 'list[InlineResponse20071ShowpoolsresponsePools]'
    }

    attribute_map = {
        'status': 'status',
        'pools_count': 'pools-count',
        'pools': 'pools'
    }

    def __init__(self, status=None, pools_count=None, pools=None, _configuration=None):  # noqa: E501
        """InlineResponse20071Showpoolsresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._pools_count = None
        self._pools = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if pools_count is not None:
            self.pools_count = pools_count
        if pools is not None:
            self.pools = pools

    @property
    def status(self):
        """Gets the status of this InlineResponse20071Showpoolsresponse.  # noqa: E501


        :return: The status of this InlineResponse20071Showpoolsresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20071Showpoolsresponse.


        :param status: The status of this InlineResponse20071Showpoolsresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def pools_count(self):
        """Gets the pools_count of this InlineResponse20071Showpoolsresponse.  # noqa: E501


        :return: The pools_count of this InlineResponse20071Showpoolsresponse.  # noqa: E501
        :rtype: int
        """
        return self._pools_count

    @pools_count.setter
    def pools_count(self, pools_count):
        """Sets the pools_count of this InlineResponse20071Showpoolsresponse.


        :param pools_count: The pools_count of this InlineResponse20071Showpoolsresponse.  # noqa: E501
        :type: int
        """

        self._pools_count = pools_count

    @property
    def pools(self):
        """Gets the pools of this InlineResponse20071Showpoolsresponse.  # noqa: E501


        :return: The pools of this InlineResponse20071Showpoolsresponse.  # noqa: E501
        :rtype: list[InlineResponse20071ShowpoolsresponsePools]
        """
        return self._pools

    @pools.setter
    def pools(self, pools):
        """Sets the pools of this InlineResponse20071Showpoolsresponse.


        :param pools: The pools of this InlineResponse20071Showpoolsresponse.  # noqa: E501
        :type: list[InlineResponse20071ShowpoolsresponsePools]
        """

        self._pools = pools

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20071Showpoolsresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20071Showpoolsresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20071Showpoolsresponse):
            return True

        return self.to_dict() != other.to_dict()
