# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse200190Showsnapshotpoliciesresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'snapshot_policies_count': 'int',
        'snapshot_policies': 'list[InlineResponse200190ShowsnapshotpoliciesresponseSnapshotpolicies]'
    }

    attribute_map = {
        'status': 'status',
        'snapshot_policies_count': 'snapshot-policies-count',
        'snapshot_policies': 'snapshot-policies'
    }

    def __init__(self, status=None, snapshot_policies_count=None, snapshot_policies=None, _configuration=None):  # noqa: E501
        """InlineResponse200190Showsnapshotpoliciesresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._snapshot_policies_count = None
        self._snapshot_policies = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if snapshot_policies_count is not None:
            self.snapshot_policies_count = snapshot_policies_count
        if snapshot_policies is not None:
            self.snapshot_policies = snapshot_policies

    @property
    def status(self):
        """Gets the status of this InlineResponse200190Showsnapshotpoliciesresponse.  # noqa: E501


        :return: The status of this InlineResponse200190Showsnapshotpoliciesresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200190Showsnapshotpoliciesresponse.


        :param status: The status of this InlineResponse200190Showsnapshotpoliciesresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def snapshot_policies_count(self):
        """Gets the snapshot_policies_count of this InlineResponse200190Showsnapshotpoliciesresponse.  # noqa: E501


        :return: The snapshot_policies_count of this InlineResponse200190Showsnapshotpoliciesresponse.  # noqa: E501
        :rtype: int
        """
        return self._snapshot_policies_count

    @snapshot_policies_count.setter
    def snapshot_policies_count(self, snapshot_policies_count):
        """Sets the snapshot_policies_count of this InlineResponse200190Showsnapshotpoliciesresponse.


        :param snapshot_policies_count: The snapshot_policies_count of this InlineResponse200190Showsnapshotpoliciesresponse.  # noqa: E501
        :type: int
        """

        self._snapshot_policies_count = snapshot_policies_count

    @property
    def snapshot_policies(self):
        """Gets the snapshot_policies of this InlineResponse200190Showsnapshotpoliciesresponse.  # noqa: E501


        :return: The snapshot_policies of this InlineResponse200190Showsnapshotpoliciesresponse.  # noqa: E501
        :rtype: list[InlineResponse200190ShowsnapshotpoliciesresponseSnapshotpolicies]
        """
        return self._snapshot_policies

    @snapshot_policies.setter
    def snapshot_policies(self, snapshot_policies):
        """Sets the snapshot_policies of this InlineResponse200190Showsnapshotpoliciesresponse.


        :param snapshot_policies: The snapshot_policies of this InlineResponse200190Showsnapshotpoliciesresponse.  # noqa: E501
        :type: list[InlineResponse200190ShowsnapshotpoliciesresponseSnapshotpolicies]
        """

        self._snapshot_policies = snapshot_policies

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200190Showsnapshotpoliciesresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200190Showsnapshotpoliciesresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200190Showsnapshotpoliciesresponse):
            return True

        return self.to_dict() != other.to_dict()
