# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse2005ShowQuarantinedFilesresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'quarantine_files_count': 'int',
        'quarantine_files': 'list[InlineResponse2005ShowQuarantinedFilesresponseQuarantinefiles]'
    }

    attribute_map = {
        'status': 'status',
        'quarantine_files_count': 'quarantine-files-count',
        'quarantine_files': 'quarantine-files'
    }

    def __init__(self, status=None, quarantine_files_count=None, quarantine_files=None, _configuration=None):  # noqa: E501
        """InlineResponse2005ShowQuarantinedFilesresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._quarantine_files_count = None
        self._quarantine_files = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if quarantine_files_count is not None:
            self.quarantine_files_count = quarantine_files_count
        if quarantine_files is not None:
            self.quarantine_files = quarantine_files

    @property
    def status(self):
        """Gets the status of this InlineResponse2005ShowQuarantinedFilesresponse.  # noqa: E501


        :return: The status of this InlineResponse2005ShowQuarantinedFilesresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse2005ShowQuarantinedFilesresponse.


        :param status: The status of this InlineResponse2005ShowQuarantinedFilesresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def quarantine_files_count(self):
        """Gets the quarantine_files_count of this InlineResponse2005ShowQuarantinedFilesresponse.  # noqa: E501


        :return: The quarantine_files_count of this InlineResponse2005ShowQuarantinedFilesresponse.  # noqa: E501
        :rtype: int
        """
        return self._quarantine_files_count

    @quarantine_files_count.setter
    def quarantine_files_count(self, quarantine_files_count):
        """Sets the quarantine_files_count of this InlineResponse2005ShowQuarantinedFilesresponse.


        :param quarantine_files_count: The quarantine_files_count of this InlineResponse2005ShowQuarantinedFilesresponse.  # noqa: E501
        :type: int
        """

        self._quarantine_files_count = quarantine_files_count

    @property
    def quarantine_files(self):
        """Gets the quarantine_files of this InlineResponse2005ShowQuarantinedFilesresponse.  # noqa: E501


        :return: The quarantine_files of this InlineResponse2005ShowQuarantinedFilesresponse.  # noqa: E501
        :rtype: list[InlineResponse2005ShowQuarantinedFilesresponseQuarantinefiles]
        """
        return self._quarantine_files

    @quarantine_files.setter
    def quarantine_files(self, quarantine_files):
        """Sets the quarantine_files of this InlineResponse2005ShowQuarantinedFilesresponse.


        :param quarantine_files: The quarantine_files of this InlineResponse2005ShowQuarantinedFilesresponse.  # noqa: E501
        :type: list[InlineResponse2005ShowQuarantinedFilesresponseQuarantinefiles]
        """

        self._quarantine_files = quarantine_files

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2005ShowQuarantinedFilesresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2005ShowQuarantinedFilesresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse2005ShowQuarantinedFilesresponse):
            return True

        return self.to_dict() != other.to_dict()
