# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse20042Showonelifecyclepolicyresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'life_cycle_policy': 'InlineResponse20042ShowonelifecyclepolicyresponseLifecyclepolicy'
    }

    attribute_map = {
        'status': 'status',
        'life_cycle_policy': 'life-cycle-policy'
    }

    def __init__(self, status=None, life_cycle_policy=None, _configuration=None):  # noqa: E501
        """InlineResponse20042Showonelifecyclepolicyresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._life_cycle_policy = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if life_cycle_policy is not None:
            self.life_cycle_policy = life_cycle_policy

    @property
    def status(self):
        """Gets the status of this InlineResponse20042Showonelifecyclepolicyresponse.  # noqa: E501


        :return: The status of this InlineResponse20042Showonelifecyclepolicyresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20042Showonelifecyclepolicyresponse.


        :param status: The status of this InlineResponse20042Showonelifecyclepolicyresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def life_cycle_policy(self):
        """Gets the life_cycle_policy of this InlineResponse20042Showonelifecyclepolicyresponse.  # noqa: E501


        :return: The life_cycle_policy of this InlineResponse20042Showonelifecyclepolicyresponse.  # noqa: E501
        :rtype: InlineResponse20042ShowonelifecyclepolicyresponseLifecyclepolicy
        """
        return self._life_cycle_policy

    @life_cycle_policy.setter
    def life_cycle_policy(self, life_cycle_policy):
        """Sets the life_cycle_policy of this InlineResponse20042Showonelifecyclepolicyresponse.


        :param life_cycle_policy: The life_cycle_policy of this InlineResponse20042Showonelifecyclepolicyresponse.  # noqa: E501
        :type: InlineResponse20042ShowonelifecyclepolicyresponseLifecyclepolicy
        """

        self._life_cycle_policy = life_cycle_policy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20042Showonelifecyclepolicyresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20042Showonelifecyclepolicyresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20042Showonelifecyclepolicyresponse):
            return True

        return self.to_dict() != other.to_dict()
