# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse200258Response(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'from_date_time': 'datetime',
        'to_date_time': 'datetime'
    }

    attribute_map = {
        'from_date_time': 'from-date-time',
        'to_date_time': 'to-date-time'
    }

    def __init__(self, from_date_time=None, to_date_time=None, _configuration=None):  # noqa: E501
        """InlineResponse200258Response - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._from_date_time = None
        self._to_date_time = None
        self.discriminator = None

        if from_date_time is not None:
            self.from_date_time = from_date_time
        if to_date_time is not None:
            self.to_date_time = to_date_time

    @property
    def from_date_time(self):
        """Gets the from_date_time of this InlineResponse200258Response.  # noqa: E501


        :return: The from_date_time of this InlineResponse200258Response.  # noqa: E501
        :rtype: datetime
        """
        return self._from_date_time

    @from_date_time.setter
    def from_date_time(self, from_date_time):
        """Sets the from_date_time of this InlineResponse200258Response.


        :param from_date_time: The from_date_time of this InlineResponse200258Response.  # noqa: E501
        :type: datetime
        """

        self._from_date_time = from_date_time

    @property
    def to_date_time(self):
        """Gets the to_date_time of this InlineResponse200258Response.  # noqa: E501


        :return: The to_date_time of this InlineResponse200258Response.  # noqa: E501
        :rtype: datetime
        """
        return self._to_date_time

    @to_date_time.setter
    def to_date_time(self, to_date_time):
        """Sets the to_date_time of this InlineResponse200258Response.


        :param to_date_time: The to_date_time of this InlineResponse200258Response.  # noqa: E501
        :type: datetime
        """

        self._to_date_time = to_date_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200258Response, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200258Response):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200258Response):
            return True

        return self.to_dict() != other.to_dict()
