# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse200188(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'set_mtu_response': 'InlineResponse2006RestoreDelQuarantineFileresponse'
    }

    attribute_map = {
        'set_mtu_response': 'set-mtu-response'
    }

    def __init__(self, set_mtu_response=None, _configuration=None):  # noqa: E501
        """InlineResponse200188 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._set_mtu_response = None
        self.discriminator = None

        if set_mtu_response is not None:
            self.set_mtu_response = set_mtu_response

    @property
    def set_mtu_response(self):
        """Gets the set_mtu_response of this InlineResponse200188.  # noqa: E501


        :return: The set_mtu_response of this InlineResponse200188.  # noqa: E501
        :rtype: InlineResponse2006RestoreDelQuarantineFileresponse
        """
        return self._set_mtu_response

    @set_mtu_response.setter
    def set_mtu_response(self, set_mtu_response):
        """Sets the set_mtu_response of this InlineResponse200188.


        :param set_mtu_response: The set_mtu_response of this InlineResponse200188.  # noqa: E501
        :type: InlineResponse2006RestoreDelQuarantineFileresponse
        """

        self._set_mtu_response = set_mtu_response

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200188, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200188):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200188):
            return True

        return self.to_dict() != other.to_dict()
