# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse200137Showoneobsbackupjobresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'obs_backup_job': 'InlineResponse200137ShowoneobsbackupjobresponseObsbackupjob'
    }

    attribute_map = {
        'status': 'status',
        'obs_backup_job': 'obs-backup-job'
    }

    def __init__(self, status=None, obs_backup_job=None, _configuration=None):  # noqa: E501
        """InlineResponse200137Showoneobsbackupjobresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._obs_backup_job = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if obs_backup_job is not None:
            self.obs_backup_job = obs_backup_job

    @property
    def status(self):
        """Gets the status of this InlineResponse200137Showoneobsbackupjobresponse.  # noqa: E501


        :return: The status of this InlineResponse200137Showoneobsbackupjobresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200137Showoneobsbackupjobresponse.


        :param status: The status of this InlineResponse200137Showoneobsbackupjobresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def obs_backup_job(self):
        """Gets the obs_backup_job of this InlineResponse200137Showoneobsbackupjobresponse.  # noqa: E501


        :return: The obs_backup_job of this InlineResponse200137Showoneobsbackupjobresponse.  # noqa: E501
        :rtype: InlineResponse200137ShowoneobsbackupjobresponseObsbackupjob
        """
        return self._obs_backup_job

    @obs_backup_job.setter
    def obs_backup_job(self, obs_backup_job):
        """Sets the obs_backup_job of this InlineResponse200137Showoneobsbackupjobresponse.


        :param obs_backup_job: The obs_backup_job of this InlineResponse200137Showoneobsbackupjobresponse.  # noqa: E501
        :type: InlineResponse200137ShowoneobsbackupjobresponseObsbackupjob
        """

        self._obs_backup_job = obs_backup_job

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200137Showoneobsbackupjobresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200137Showoneobsbackupjobresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200137Showoneobsbackupjobresponse):
            return True

        return self.to_dict() != other.to_dict()
