# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse20024Showvcontrollersresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'vcontrollers_count': 'int',
        'vcontrollers': 'list[InlineResponse20024ShowvcontrollersresponseVcontrollers]'
    }

    attribute_map = {
        'status': 'status',
        'vcontrollers_count': 'vcontrollers-count',
        'vcontrollers': 'vcontrollers'
    }

    def __init__(self, status=None, vcontrollers_count=None, vcontrollers=None, _configuration=None):  # noqa: E501
        """InlineResponse20024Showvcontrollersresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._vcontrollers_count = None
        self._vcontrollers = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if vcontrollers_count is not None:
            self.vcontrollers_count = vcontrollers_count
        if vcontrollers is not None:
            self.vcontrollers = vcontrollers

    @property
    def status(self):
        """Gets the status of this InlineResponse20024Showvcontrollersresponse.  # noqa: E501


        :return: The status of this InlineResponse20024Showvcontrollersresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20024Showvcontrollersresponse.


        :param status: The status of this InlineResponse20024Showvcontrollersresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def vcontrollers_count(self):
        """Gets the vcontrollers_count of this InlineResponse20024Showvcontrollersresponse.  # noqa: E501


        :return: The vcontrollers_count of this InlineResponse20024Showvcontrollersresponse.  # noqa: E501
        :rtype: int
        """
        return self._vcontrollers_count

    @vcontrollers_count.setter
    def vcontrollers_count(self, vcontrollers_count):
        """Sets the vcontrollers_count of this InlineResponse20024Showvcontrollersresponse.


        :param vcontrollers_count: The vcontrollers_count of this InlineResponse20024Showvcontrollersresponse.  # noqa: E501
        :type: int
        """

        self._vcontrollers_count = vcontrollers_count

    @property
    def vcontrollers(self):
        """Gets the vcontrollers of this InlineResponse20024Showvcontrollersresponse.  # noqa: E501


        :return: The vcontrollers of this InlineResponse20024Showvcontrollersresponse.  # noqa: E501
        :rtype: list[InlineResponse20024ShowvcontrollersresponseVcontrollers]
        """
        return self._vcontrollers

    @vcontrollers.setter
    def vcontrollers(self, vcontrollers):
        """Sets the vcontrollers of this InlineResponse20024Showvcontrollersresponse.


        :param vcontrollers: The vcontrollers of this InlineResponse20024Showvcontrollersresponse.  # noqa: E501
        :type: list[InlineResponse20024ShowvcontrollersresponseVcontrollers]
        """

        self._vcontrollers = vcontrollers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20024Showvcontrollersresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20024Showvcontrollersresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20024Showvcontrollersresponse):
            return True

        return self.to_dict() != other.to_dict()
