# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse20045Showflccategoriesresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'categories_count': 'int',
        'categories': 'list[InlineResponse20045ShowflccategoriesresponseCategories]'
    }

    attribute_map = {
        'status': 'status',
        'categories_count': 'categories-count',
        'categories': 'categories'
    }

    def __init__(self, status=None, categories_count=None, categories=None, _configuration=None):  # noqa: E501
        """InlineResponse20045Showflccategoriesresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._categories_count = None
        self._categories = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if categories_count is not None:
            self.categories_count = categories_count
        if categories is not None:
            self.categories = categories

    @property
    def status(self):
        """Gets the status of this InlineResponse20045Showflccategoriesresponse.  # noqa: E501


        :return: The status of this InlineResponse20045Showflccategoriesresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20045Showflccategoriesresponse.


        :param status: The status of this InlineResponse20045Showflccategoriesresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def categories_count(self):
        """Gets the categories_count of this InlineResponse20045Showflccategoriesresponse.  # noqa: E501


        :return: The categories_count of this InlineResponse20045Showflccategoriesresponse.  # noqa: E501
        :rtype: int
        """
        return self._categories_count

    @categories_count.setter
    def categories_count(self, categories_count):
        """Sets the categories_count of this InlineResponse20045Showflccategoriesresponse.


        :param categories_count: The categories_count of this InlineResponse20045Showflccategoriesresponse.  # noqa: E501
        :type: int
        """

        self._categories_count = categories_count

    @property
    def categories(self):
        """Gets the categories of this InlineResponse20045Showflccategoriesresponse.  # noqa: E501


        :return: The categories of this InlineResponse20045Showflccategoriesresponse.  # noqa: E501
        :rtype: list[InlineResponse20045ShowflccategoriesresponseCategories]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """Sets the categories of this InlineResponse20045Showflccategoriesresponse.


        :param categories: The categories of this InlineResponse20045Showflccategoriesresponse.  # noqa: E501
        :type: list[InlineResponse20045ShowflccategoriesresponseCategories]
        """

        self._categories = categories

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20045Showflccategoriesresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20045Showflccategoriesresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20045Showflccategoriesresponse):
            return True

        return self.to_dict() != other.to_dict()
