# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse20076Showraidgroupsinpoolresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'raid_groups_count': 'int',
        'raid_groups': 'list[InlineResponse20076ShowraidgroupsinpoolresponseRaidgroups]'
    }

    attribute_map = {
        'status': 'status',
        'raid_groups_count': 'raid-groups-count',
        'raid_groups': 'raid-groups'
    }

    def __init__(self, status=None, raid_groups_count=None, raid_groups=None, _configuration=None):  # noqa: E501
        """InlineResponse20076Showraidgroupsinpoolresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._raid_groups_count = None
        self._raid_groups = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if raid_groups_count is not None:
            self.raid_groups_count = raid_groups_count
        if raid_groups is not None:
            self.raid_groups = raid_groups

    @property
    def status(self):
        """Gets the status of this InlineResponse20076Showraidgroupsinpoolresponse.  # noqa: E501


        :return: The status of this InlineResponse20076Showraidgroupsinpoolresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20076Showraidgroupsinpoolresponse.


        :param status: The status of this InlineResponse20076Showraidgroupsinpoolresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def raid_groups_count(self):
        """Gets the raid_groups_count of this InlineResponse20076Showraidgroupsinpoolresponse.  # noqa: E501


        :return: The raid_groups_count of this InlineResponse20076Showraidgroupsinpoolresponse.  # noqa: E501
        :rtype: int
        """
        return self._raid_groups_count

    @raid_groups_count.setter
    def raid_groups_count(self, raid_groups_count):
        """Sets the raid_groups_count of this InlineResponse20076Showraidgroupsinpoolresponse.


        :param raid_groups_count: The raid_groups_count of this InlineResponse20076Showraidgroupsinpoolresponse.  # noqa: E501
        :type: int
        """

        self._raid_groups_count = raid_groups_count

    @property
    def raid_groups(self):
        """Gets the raid_groups of this InlineResponse20076Showraidgroupsinpoolresponse.  # noqa: E501


        :return: The raid_groups of this InlineResponse20076Showraidgroupsinpoolresponse.  # noqa: E501
        :rtype: list[InlineResponse20076ShowraidgroupsinpoolresponseRaidgroups]
        """
        return self._raid_groups

    @raid_groups.setter
    def raid_groups(self, raid_groups):
        """Sets the raid_groups of this InlineResponse20076Showraidgroupsinpoolresponse.


        :param raid_groups: The raid_groups of this InlineResponse20076Showraidgroupsinpoolresponse.  # noqa: E501
        :type: list[InlineResponse20076ShowraidgroupsinpoolresponseRaidgroups]
        """

        self._raid_groups = raid_groups

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20076Showraidgroupsinpoolresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20076Showraidgroupsinpoolresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20076Showraidgroupsinpoolresponse):
            return True

        return self.to_dict() != other.to_dict()
