# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse20029GetZcachePerfresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'zcache_name': 'str',
        'status': 'int',
        'zcache_usages_count': 'int',
        'zcache_usages': 'list[InlineResponse20029GetZcachePerfresponseZcacheusages]'
    }

    attribute_map = {
        'zcache_name': 'zcache-name',
        'status': 'status',
        'zcache_usages_count': 'zcache-usages-count',
        'zcache_usages': 'zcache-usages'
    }

    def __init__(self, zcache_name=None, status=None, zcache_usages_count=None, zcache_usages=None, _configuration=None):  # noqa: E501
        """InlineResponse20029GetZcachePerfresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._zcache_name = None
        self._status = None
        self._zcache_usages_count = None
        self._zcache_usages = None
        self.discriminator = None

        if zcache_name is not None:
            self.zcache_name = zcache_name
        if status is not None:
            self.status = status
        if zcache_usages_count is not None:
            self.zcache_usages_count = zcache_usages_count
        if zcache_usages is not None:
            self.zcache_usages = zcache_usages

    @property
    def zcache_name(self):
        """Gets the zcache_name of this InlineResponse20029GetZcachePerfresponse.  # noqa: E501


        :return: The zcache_name of this InlineResponse20029GetZcachePerfresponse.  # noqa: E501
        :rtype: str
        """
        return self._zcache_name

    @zcache_name.setter
    def zcache_name(self, zcache_name):
        """Sets the zcache_name of this InlineResponse20029GetZcachePerfresponse.


        :param zcache_name: The zcache_name of this InlineResponse20029GetZcachePerfresponse.  # noqa: E501
        :type: str
        """

        self._zcache_name = zcache_name

    @property
    def status(self):
        """Gets the status of this InlineResponse20029GetZcachePerfresponse.  # noqa: E501


        :return: The status of this InlineResponse20029GetZcachePerfresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20029GetZcachePerfresponse.


        :param status: The status of this InlineResponse20029GetZcachePerfresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def zcache_usages_count(self):
        """Gets the zcache_usages_count of this InlineResponse20029GetZcachePerfresponse.  # noqa: E501


        :return: The zcache_usages_count of this InlineResponse20029GetZcachePerfresponse.  # noqa: E501
        :rtype: int
        """
        return self._zcache_usages_count

    @zcache_usages_count.setter
    def zcache_usages_count(self, zcache_usages_count):
        """Sets the zcache_usages_count of this InlineResponse20029GetZcachePerfresponse.


        :param zcache_usages_count: The zcache_usages_count of this InlineResponse20029GetZcachePerfresponse.  # noqa: E501
        :type: int
        """

        self._zcache_usages_count = zcache_usages_count

    @property
    def zcache_usages(self):
        """Gets the zcache_usages of this InlineResponse20029GetZcachePerfresponse.  # noqa: E501


        :return: The zcache_usages of this InlineResponse20029GetZcachePerfresponse.  # noqa: E501
        :rtype: list[InlineResponse20029GetZcachePerfresponseZcacheusages]
        """
        return self._zcache_usages

    @zcache_usages.setter
    def zcache_usages(self, zcache_usages):
        """Sets the zcache_usages of this InlineResponse20029GetZcachePerfresponse.


        :param zcache_usages: The zcache_usages of this InlineResponse20029GetZcachePerfresponse.  # noqa: E501
        :type: list[InlineResponse20029GetZcachePerfresponseZcacheusages]
        """

        self._zcache_usages = zcache_usages

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20029GetZcachePerfresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20029GetZcachePerfresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20029GetZcachePerfresponse):
            return True

        return self.to_dict() != other.to_dict()
