# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse200199Showuserticketsresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'tickets_count': 'int',
        'tickets': 'list[InlineResponse200199ShowuserticketsresponseTickets]'
    }

    attribute_map = {
        'status': 'status',
        'tickets_count': 'tickets-count',
        'tickets': 'tickets'
    }

    def __init__(self, status=None, tickets_count=None, tickets=None, _configuration=None):  # noqa: E501
        """InlineResponse200199Showuserticketsresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._tickets_count = None
        self._tickets = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if tickets_count is not None:
            self.tickets_count = tickets_count
        if tickets is not None:
            self.tickets = tickets

    @property
    def status(self):
        """Gets the status of this InlineResponse200199Showuserticketsresponse.  # noqa: E501


        :return: The status of this InlineResponse200199Showuserticketsresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200199Showuserticketsresponse.


        :param status: The status of this InlineResponse200199Showuserticketsresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def tickets_count(self):
        """Gets the tickets_count of this InlineResponse200199Showuserticketsresponse.  # noqa: E501


        :return: The tickets_count of this InlineResponse200199Showuserticketsresponse.  # noqa: E501
        :rtype: int
        """
        return self._tickets_count

    @tickets_count.setter
    def tickets_count(self, tickets_count):
        """Sets the tickets_count of this InlineResponse200199Showuserticketsresponse.


        :param tickets_count: The tickets_count of this InlineResponse200199Showuserticketsresponse.  # noqa: E501
        :type: int
        """

        self._tickets_count = tickets_count

    @property
    def tickets(self):
        """Gets the tickets of this InlineResponse200199Showuserticketsresponse.  # noqa: E501


        :return: The tickets of this InlineResponse200199Showuserticketsresponse.  # noqa: E501
        :rtype: list[InlineResponse200199ShowuserticketsresponseTickets]
        """
        return self._tickets

    @tickets.setter
    def tickets(self, tickets):
        """Sets the tickets of this InlineResponse200199Showuserticketsresponse.


        :param tickets: The tickets of this InlineResponse200199Showuserticketsresponse.  # noqa: E501
        :type: list[InlineResponse200199ShowuserticketsresponseTickets]
        """

        self._tickets = tickets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200199Showuserticketsresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200199Showuserticketsresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200199Showuserticketsresponse):
            return True

        return self.to_dict() != other.to_dict()
