# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse200196Response(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'volumes_count': 'int',
        'volumes': 'list[InlineResponse200196ResponseVolumes]'
    }

    attribute_map = {
        'status': 'status',
        'volumes_count': 'volumes-count',
        'volumes': 'volumes'
    }

    def __init__(self, status=None, volumes_count=None, volumes=None, _configuration=None):  # noqa: E501
        """InlineResponse200196Response - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._volumes_count = None
        self._volumes = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if volumes_count is not None:
            self.volumes_count = volumes_count
        if volumes is not None:
            self.volumes = volumes

    @property
    def status(self):
        """Gets the status of this InlineResponse200196Response.  # noqa: E501


        :return: The status of this InlineResponse200196Response.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200196Response.


        :param status: The status of this InlineResponse200196Response.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def volumes_count(self):
        """Gets the volumes_count of this InlineResponse200196Response.  # noqa: E501


        :return: The volumes_count of this InlineResponse200196Response.  # noqa: E501
        :rtype: int
        """
        return self._volumes_count

    @volumes_count.setter
    def volumes_count(self, volumes_count):
        """Sets the volumes_count of this InlineResponse200196Response.


        :param volumes_count: The volumes_count of this InlineResponse200196Response.  # noqa: E501
        :type: int
        """

        self._volumes_count = volumes_count

    @property
    def volumes(self):
        """Gets the volumes of this InlineResponse200196Response.  # noqa: E501


        :return: The volumes of this InlineResponse200196Response.  # noqa: E501
        :rtype: list[InlineResponse200196ResponseVolumes]
        """
        return self._volumes

    @volumes.setter
    def volumes(self, volumes):
        """Sets the volumes of this InlineResponse200196Response.


        :param volumes: The volumes of this InlineResponse200196Response.  # noqa: E501
        :type: list[InlineResponse200196ResponseVolumes]
        """

        self._volumes = volumes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200196Response, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200196Response):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200196Response):
            return True

        return self.to_dict() != other.to_dict()
