# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse20062Shownasgroupsresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'groups_count': 'int',
        'groups': 'list[InlineResponse20062ShownasgroupsresponseGroups]'
    }

    attribute_map = {
        'status': 'status',
        'groups_count': 'groups-count',
        'groups': 'groups'
    }

    def __init__(self, status=None, groups_count=None, groups=None, _configuration=None):  # noqa: E501
        """InlineResponse20062Shownasgroupsresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._groups_count = None
        self._groups = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if groups_count is not None:
            self.groups_count = groups_count
        if groups is not None:
            self.groups = groups

    @property
    def status(self):
        """Gets the status of this InlineResponse20062Shownasgroupsresponse.  # noqa: E501


        :return: The status of this InlineResponse20062Shownasgroupsresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20062Shownasgroupsresponse.


        :param status: The status of this InlineResponse20062Shownasgroupsresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def groups_count(self):
        """Gets the groups_count of this InlineResponse20062Shownasgroupsresponse.  # noqa: E501


        :return: The groups_count of this InlineResponse20062Shownasgroupsresponse.  # noqa: E501
        :rtype: int
        """
        return self._groups_count

    @groups_count.setter
    def groups_count(self, groups_count):
        """Sets the groups_count of this InlineResponse20062Shownasgroupsresponse.


        :param groups_count: The groups_count of this InlineResponse20062Shownasgroupsresponse.  # noqa: E501
        :type: int
        """

        self._groups_count = groups_count

    @property
    def groups(self):
        """Gets the groups of this InlineResponse20062Shownasgroupsresponse.  # noqa: E501


        :return: The groups of this InlineResponse20062Shownasgroupsresponse.  # noqa: E501
        :rtype: list[InlineResponse20062ShownasgroupsresponseGroups]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this InlineResponse20062Shownasgroupsresponse.


        :param groups: The groups of this InlineResponse20062Shownasgroupsresponse.  # noqa: E501
        :type: list[InlineResponse20062ShownasgroupsresponseGroups]
        """

        self._groups = groups

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20062Shownasgroupsresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20062Shownasgroupsresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20062Shownasgroupsresponse):
            return True

        return self.to_dict() != other.to_dict()
