# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse200248Showquotaprojectsresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'projects_count': 'int',
        'projects': 'list[InlineResponse200248ShowquotaprojectsresponseProjects]'
    }

    attribute_map = {
        'status': 'status',
        'projects_count': 'projects-count',
        'projects': 'projects'
    }

    def __init__(self, status=None, projects_count=None, projects=None, _configuration=None):  # noqa: E501
        """InlineResponse200248Showquotaprojectsresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._projects_count = None
        self._projects = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if projects_count is not None:
            self.projects_count = projects_count
        if projects is not None:
            self.projects = projects

    @property
    def status(self):
        """Gets the status of this InlineResponse200248Showquotaprojectsresponse.  # noqa: E501


        :return: The status of this InlineResponse200248Showquotaprojectsresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200248Showquotaprojectsresponse.


        :param status: The status of this InlineResponse200248Showquotaprojectsresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def projects_count(self):
        """Gets the projects_count of this InlineResponse200248Showquotaprojectsresponse.  # noqa: E501


        :return: The projects_count of this InlineResponse200248Showquotaprojectsresponse.  # noqa: E501
        :rtype: int
        """
        return self._projects_count

    @projects_count.setter
    def projects_count(self, projects_count):
        """Sets the projects_count of this InlineResponse200248Showquotaprojectsresponse.


        :param projects_count: The projects_count of this InlineResponse200248Showquotaprojectsresponse.  # noqa: E501
        :type: int
        """

        self._projects_count = projects_count

    @property
    def projects(self):
        """Gets the projects of this InlineResponse200248Showquotaprojectsresponse.  # noqa: E501


        :return: The projects of this InlineResponse200248Showquotaprojectsresponse.  # noqa: E501
        :rtype: list[InlineResponse200248ShowquotaprojectsresponseProjects]
        """
        return self._projects

    @projects.setter
    def projects(self, projects):
        """Sets the projects of this InlineResponse200248Showquotaprojectsresponse.


        :param projects: The projects of this InlineResponse200248Showquotaprojectsresponse.  # noqa: E501
        :type: list[InlineResponse200248ShowquotaprojectsresponseProjects]
        """

        self._projects = projects

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200248Showquotaprojectsresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200248Showquotaprojectsresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200248Showquotaprojectsresponse):
            return True

        return self.to_dict() != other.to_dict()
