# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse20025Showvnisresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'vnis_count': 'int',
        'vnis': 'list[InlineResponse20025ShowvnisresponseVnis]'
    }

    attribute_map = {
        'status': 'status',
        'vnis_count': 'vnis-count',
        'vnis': 'vnis'
    }

    def __init__(self, status=None, vnis_count=None, vnis=None, _configuration=None):  # noqa: E501
        """InlineResponse20025Showvnisresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._vnis_count = None
        self._vnis = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if vnis_count is not None:
            self.vnis_count = vnis_count
        if vnis is not None:
            self.vnis = vnis

    @property
    def status(self):
        """Gets the status of this InlineResponse20025Showvnisresponse.  # noqa: E501


        :return: The status of this InlineResponse20025Showvnisresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20025Showvnisresponse.


        :param status: The status of this InlineResponse20025Showvnisresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def vnis_count(self):
        """Gets the vnis_count of this InlineResponse20025Showvnisresponse.  # noqa: E501


        :return: The vnis_count of this InlineResponse20025Showvnisresponse.  # noqa: E501
        :rtype: int
        """
        return self._vnis_count

    @vnis_count.setter
    def vnis_count(self, vnis_count):
        """Sets the vnis_count of this InlineResponse20025Showvnisresponse.


        :param vnis_count: The vnis_count of this InlineResponse20025Showvnisresponse.  # noqa: E501
        :type: int
        """

        self._vnis_count = vnis_count

    @property
    def vnis(self):
        """Gets the vnis of this InlineResponse20025Showvnisresponse.  # noqa: E501


        :return: The vnis of this InlineResponse20025Showvnisresponse.  # noqa: E501
        :rtype: list[InlineResponse20025ShowvnisresponseVnis]
        """
        return self._vnis

    @vnis.setter
    def vnis(self, vnis):
        """Sets the vnis of this InlineResponse20025Showvnisresponse.


        :param vnis: The vnis of this InlineResponse20025Showvnisresponse.  # noqa: E501
        :type: list[InlineResponse20025ShowvnisresponseVnis]
        """

        self._vnis = vnis

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20025Showvnisresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20025Showvnisresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20025Showvnisresponse):
            return True

        return self.to_dict() != other.to_dict()
