# coding: utf-8

"""
    VPSA api

    VPSA operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from vpsa.configuration import Configuration


class InlineResponse200158Showserversresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'servers_count': 'int',
        'servers': 'list[InlineResponse200158ShowserversresponseServers]'
    }

    attribute_map = {
        'status': 'status',
        'servers_count': 'servers-count',
        'servers': 'servers'
    }

    def __init__(self, status=None, servers_count=None, servers=None, _configuration=None):  # noqa: E501
        """InlineResponse200158Showserversresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._servers_count = None
        self._servers = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if servers_count is not None:
            self.servers_count = servers_count
        if servers is not None:
            self.servers = servers

    @property
    def status(self):
        """Gets the status of this InlineResponse200158Showserversresponse.  # noqa: E501


        :return: The status of this InlineResponse200158Showserversresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse200158Showserversresponse.


        :param status: The status of this InlineResponse200158Showserversresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def servers_count(self):
        """Gets the servers_count of this InlineResponse200158Showserversresponse.  # noqa: E501


        :return: The servers_count of this InlineResponse200158Showserversresponse.  # noqa: E501
        :rtype: int
        """
        return self._servers_count

    @servers_count.setter
    def servers_count(self, servers_count):
        """Sets the servers_count of this InlineResponse200158Showserversresponse.


        :param servers_count: The servers_count of this InlineResponse200158Showserversresponse.  # noqa: E501
        :type: int
        """

        self._servers_count = servers_count

    @property
    def servers(self):
        """Gets the servers of this InlineResponse200158Showserversresponse.  # noqa: E501


        :return: The servers of this InlineResponse200158Showserversresponse.  # noqa: E501
        :rtype: list[InlineResponse200158ShowserversresponseServers]
        """
        return self._servers

    @servers.setter
    def servers(self, servers):
        """Sets the servers of this InlineResponse200158Showserversresponse.


        :param servers: The servers of this InlineResponse200158Showserversresponse.  # noqa: E501
        :type: list[InlineResponse200158ShowserversresponseServers]
        """

        self._servers = servers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200158Showserversresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200158Showserversresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200158Showserversresponse):
            return True

        return self.to_dict() != other.to_dict()
