
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-04T17:54:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2283d1c456b860502c16a332b4b11aecf4a08f64",
 "version": "0.2.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
