
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-08T09:32:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9415dd268e279352b67945b1eafb8a9f3b29b0ee",
 "version": "2.2.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
