# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strmprivacy/api/organizations/v1/organizations_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7strmprivacy/api/organizations/v1/organizations_v1.proto\x12 strmprivacy.api.organizations.v1\x1a\x1fgoogle/api/field_behavior.proto\"v\n\x12InviteUsersRequest\x12G\n\x0cuser_invites\x18\x01 \x03(\x0b\x32,.strmprivacy.api.organizations.v1.UserInviteB\x03\xe0\x41\x02\x12\x17\n\x0forganization_id\x18\x02 \x01(\t\" \n\nUserInvite\x12\x12\n\x05\x65mail\x18\x01 \x01(\tB\x03\xe0\x41\x02\"\xe4\x01\n\x13InviteUsersResponse\x12\x14\n\x0cinvite_count\x18\x01 \x01(\x03\x12U\n\x06issues\x18\x02 \x03(\x0b\x32\x45.strmprivacy.api.organizations.v1.InviteUsersResponse.UserInviteIssue\x1a`\n\x0fUserInviteIssue\x12<\n\x06invite\x18\x01 \x01(\x0b\x32,.strmprivacy.api.organizations.v1.UserInvite\x12\x0f\n\x07message\x18\x02 \x01(\t2\x92\x01\n\x14OrganizationsService\x12z\n\x0bInviteUsers\x12\x34.strmprivacy.api.organizations.v1.InviteUsersRequest\x1a\x35.strmprivacy.api.organizations.v1.InviteUsersResponseBx\n#io.strmprivacy.api.organizations.v1P\x01ZOgithub.com/strmprivacy/api-definitions-go/v2/api/organizations/v1;organizationsb\x06proto3')



_INVITEUSERSREQUEST = DESCRIPTOR.message_types_by_name['InviteUsersRequest']
_USERINVITE = DESCRIPTOR.message_types_by_name['UserInvite']
_INVITEUSERSRESPONSE = DESCRIPTOR.message_types_by_name['InviteUsersResponse']
_INVITEUSERSRESPONSE_USERINVITEISSUE = _INVITEUSERSRESPONSE.nested_types_by_name['UserInviteIssue']
InviteUsersRequest = _reflection.GeneratedProtocolMessageType('InviteUsersRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVITEUSERSREQUEST,
  '__module__' : 'strmprivacy.api.organizations.v1.organizations_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.organizations.v1.InviteUsersRequest)
  })
_sym_db.RegisterMessage(InviteUsersRequest)

UserInvite = _reflection.GeneratedProtocolMessageType('UserInvite', (_message.Message,), {
  'DESCRIPTOR' : _USERINVITE,
  '__module__' : 'strmprivacy.api.organizations.v1.organizations_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.organizations.v1.UserInvite)
  })
_sym_db.RegisterMessage(UserInvite)

InviteUsersResponse = _reflection.GeneratedProtocolMessageType('InviteUsersResponse', (_message.Message,), {

  'UserInviteIssue' : _reflection.GeneratedProtocolMessageType('UserInviteIssue', (_message.Message,), {
    'DESCRIPTOR' : _INVITEUSERSRESPONSE_USERINVITEISSUE,
    '__module__' : 'strmprivacy.api.organizations.v1.organizations_v1_pb2'
    # @@protoc_insertion_point(class_scope:strmprivacy.api.organizations.v1.InviteUsersResponse.UserInviteIssue)
    })
  ,
  'DESCRIPTOR' : _INVITEUSERSRESPONSE,
  '__module__' : 'strmprivacy.api.organizations.v1.organizations_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.organizations.v1.InviteUsersResponse)
  })
_sym_db.RegisterMessage(InviteUsersResponse)
_sym_db.RegisterMessage(InviteUsersResponse.UserInviteIssue)

_ORGANIZATIONSSERVICE = DESCRIPTOR.services_by_name['OrganizationsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#io.strmprivacy.api.organizations.v1P\001ZOgithub.com/strmprivacy/api-definitions-go/v2/api/organizations/v1;organizations'
  _INVITEUSERSREQUEST.fields_by_name['user_invites']._options = None
  _INVITEUSERSREQUEST.fields_by_name['user_invites']._serialized_options = b'\340A\002'
  _USERINVITE.fields_by_name['email']._options = None
  _USERINVITE.fields_by_name['email']._serialized_options = b'\340A\002'
  _INVITEUSERSREQUEST._serialized_start=126
  _INVITEUSERSREQUEST._serialized_end=244
  _USERINVITE._serialized_start=246
  _USERINVITE._serialized_end=278
  _INVITEUSERSRESPONSE._serialized_start=281
  _INVITEUSERSRESPONSE._serialized_end=509
  _INVITEUSERSRESPONSE_USERINVITEISSUE._serialized_start=413
  _INVITEUSERSRESPONSE_USERINVITEISSUE._serialized_end=509
  _ORGANIZATIONSSERVICE._serialized_start=512
  _ORGANIZATIONSSERVICE._serialized_end=658
# @@protoc_insertion_point(module_scope)
