
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-11T11:18:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "aff66257f0df1319c8df8da3f3538524a1caef99",
 "version": "0.7.1.post.dev700"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
