
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-11T15:20:39+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "e1a2065747009f979ee03c529b38a8ecfe286a6e",
 "version": "3.8.13.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
