
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-11T16:26:47-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d49b930d970b6fb61fdcf9b7a6e6207d6137819c",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
