
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-11T11:13:30+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c509aca632ee24b5e38ff7ec80b287a59b51ac0",
 "version": "2.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
