# Generated by Django 3.2 on 2021-06-16 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('state', models.TextField(verbose_name='State')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Is passed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User check',
                'verbose_name_plural': 'User checks',
                'unique_together': {('user_id', 'reason')},
            },
        ),
    ]
