# Generated by Django 3.2 on 2021-06-24 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wcd_user_checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercheck',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Is reviewed'),
        ),
        migrations.AlterField(
            model_name='usercheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks_set', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
