
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-09T13:36:15-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "32ab1a70ca9c8ac576bdb2d95d0d45d174d6748d",
 "version": "0.5.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
