
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-10T14:56:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5af747d762ea612cab140abecbf817e0e84a7523",
 "version": "0.2.21.post0.dev20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
