
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-04T15:04:50-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9b609cb7936d99fdb08aba9d5d479831020dd1b",
 "version": "v1.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
