
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-11T09:11:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d7b41cad701071aa42b1b0be767e6f3c386ff6b",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
