
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-09T19:11:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f833bf95f2dce177885c0ac89006aa01e821ba5",
 "version": "2022.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
