VERSION_YEAR = 2022
VERSION_MONTH = int('08')
VERSION_DAY = int('10')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('15')
MAJOR_VERSION = 0
MINOR_VERSION = 7
PATCH_VERSION = 202208101615
version_date = '2022/08/10 16:15'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
