
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-05T21:48:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dbdba04eb7b9a56ea5bf2538ad10ac72761d3886",
 "version": "0.12.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
