BACKEND_PORTS = ['em3']

ETH_QUAD_CARD_SLOT_4 = ["p4p1",
                        "p4p2",
                        "p4p3",
                        "p4p4"]

ETH_QUAD_CARD_SLOT_5 = ["p5p1",
                        "p5p2",
                        "p5p3",
                        "p5p4"]

ETH_QUAD_CARD_SLOT_7 = ["p7p1",
                        "p7p2",
                        "p7p3",
                        "p7p4"]

ETH_DUAL_CARD_SLOT_4 = ["p4p1",
                        "p4p2"]

ETH_DUAL_CARD_SLOT_5 = ["p5p1",
                        "p5p2"]

ETH_DUAL_CARD_SLOT_7 = ["p7p1",
                        "p7p2"]

ETH_BLUEPRINT = {
    "default": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_4 + ETH_QUAD_CARD_SLOT_5 + ETH_QUAD_CARD_SLOT_7,
    "NOD-91101": BACKEND_PORTS,
    "NOD-91111": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_4 + ETH_QUAD_CARD_SLOT_7,
    "NOD-91121": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_4 + ETH_QUAD_CARD_SLOT_7,
    "NOD-91142": BACKEND_PORTS + ETH_DUAL_CARD_SLOT_4 + ETH_DUAL_CARD_SLOT_5 + ETH_DUAL_CARD_SLOT_7,
    "NOD-91131": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_4 + ETH_QUAD_CARD_SLOT_5 + ETH_QUAD_CARD_SLOT_7,
    "NOD-91141": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_4 + ETH_QUAD_CARD_SLOT_5 + ETH_QUAD_CARD_SLOT_7,
    "NOD-91151": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_4 + ETH_QUAD_CARD_SLOT_5 + ETH_QUAD_CARD_SLOT_7,
    "NOD-91161": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_4 + ETH_QUAD_CARD_SLOT_5 + ETH_QUAD_CARD_SLOT_7,
    "NOD-91171": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_4 + ETH_QUAD_CARD_SLOT_7,
    "NOD-91181": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_7,
    "NOD-91191": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_7,
    "NOD-92112": BACKEND_PORTS + ETH_DUAL_CARD_SLOT_4 + ETH_DUAL_CARD_SLOT_7,
    "NOD-92142": BACKEND_PORTS + ETH_DUAL_CARD_SLOT_4 + ETH_DUAL_CARD_SLOT_5 + ETH_DUAL_CARD_SLOT_7,
    "NOD-92101": BACKEND_PORTS,
    "NOD-92111": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_4 + ETH_QUAD_CARD_SLOT_7,
    "NOD-92121": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_4 + ETH_QUAD_CARD_SLOT_7,
    "NOD-92131": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_4 + ETH_QUAD_CARD_SLOT_5 + ETH_QUAD_CARD_SLOT_7,
    "NOD-92141": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_4 + ETH_QUAD_CARD_SLOT_5 + ETH_QUAD_CARD_SLOT_7,
    "NOD-92181": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_4,
    "NOD-92191": BACKEND_PORTS + ETH_QUAD_CARD_SLOT_5,
}
