
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-08T09:53:02+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "14507c94d7c5b9b38b66be5ba9fc25cee1c92b97",
 "version": "0.3.131"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
