# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/nc/nc-requests.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$zepben/protobuf/nc/nc-requests.proto\x12\x12zepben.protobuf.nc\"?\n\x1bGetIdentifiedObjectsRequest\x12\x11\n\tmessageId\x18\x01 \x01(\x03\x12\r\n\x05mrids\x18\x02 \x03(\t\"/\n\x1aGetNetworkHierarchyRequest\x12\x11\n\tmessageId\x18\x01 \x01(\x03\"D\n GetEquipmentForContainersRequest\x12\x11\n\tmessageId\x18\x01 \x01(\x03\x12\r\n\x05mrids\x18\x02 \x03(\t\"F\n#GetCurrentEquipmentForFeederRequest\x12\x11\n\tmessageId\x18\x01 \x01(\x03\x12\x0c\n\x04mrid\x18\x02 \x01(\t\"D\n!GetEquipmentForRestrictionRequest\x12\x11\n\tmessageId\x18\x01 \x01(\x03\x12\x0c\n\x04mrid\x18\x02 \x01(\t\"=\n\x1aGetTerminalsForNodeRequest\x12\x11\n\tmessageId\x18\x01 \x01(\x03\x12\x0c\n\x04mrid\x18\x02 \x01(\tB/\n\x16\x63om.zepben.protobuf.ncP\x01\xaa\x02\x12Zepben.Protobuf.NCb\x06proto3')



_GETIDENTIFIEDOBJECTSREQUEST = DESCRIPTOR.message_types_by_name['GetIdentifiedObjectsRequest']
_GETNETWORKHIERARCHYREQUEST = DESCRIPTOR.message_types_by_name['GetNetworkHierarchyRequest']
_GETEQUIPMENTFORCONTAINERSREQUEST = DESCRIPTOR.message_types_by_name['GetEquipmentForContainersRequest']
_GETCURRENTEQUIPMENTFORFEEDERREQUEST = DESCRIPTOR.message_types_by_name['GetCurrentEquipmentForFeederRequest']
_GETEQUIPMENTFORRESTRICTIONREQUEST = DESCRIPTOR.message_types_by_name['GetEquipmentForRestrictionRequest']
_GETTERMINALSFORNODEREQUEST = DESCRIPTOR.message_types_by_name['GetTerminalsForNodeRequest']
GetIdentifiedObjectsRequest = _reflection.GeneratedProtocolMessageType('GetIdentifiedObjectsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETIDENTIFIEDOBJECTSREQUEST,
  '__module__' : 'zepben.protobuf.nc.nc_requests_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.nc.GetIdentifiedObjectsRequest)
  })
_sym_db.RegisterMessage(GetIdentifiedObjectsRequest)

GetNetworkHierarchyRequest = _reflection.GeneratedProtocolMessageType('GetNetworkHierarchyRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETNETWORKHIERARCHYREQUEST,
  '__module__' : 'zepben.protobuf.nc.nc_requests_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.nc.GetNetworkHierarchyRequest)
  })
_sym_db.RegisterMessage(GetNetworkHierarchyRequest)

GetEquipmentForContainersRequest = _reflection.GeneratedProtocolMessageType('GetEquipmentForContainersRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETEQUIPMENTFORCONTAINERSREQUEST,
  '__module__' : 'zepben.protobuf.nc.nc_requests_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.nc.GetEquipmentForContainersRequest)
  })
_sym_db.RegisterMessage(GetEquipmentForContainersRequest)

GetCurrentEquipmentForFeederRequest = _reflection.GeneratedProtocolMessageType('GetCurrentEquipmentForFeederRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCURRENTEQUIPMENTFORFEEDERREQUEST,
  '__module__' : 'zepben.protobuf.nc.nc_requests_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.nc.GetCurrentEquipmentForFeederRequest)
  })
_sym_db.RegisterMessage(GetCurrentEquipmentForFeederRequest)

GetEquipmentForRestrictionRequest = _reflection.GeneratedProtocolMessageType('GetEquipmentForRestrictionRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETEQUIPMENTFORRESTRICTIONREQUEST,
  '__module__' : 'zepben.protobuf.nc.nc_requests_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.nc.GetEquipmentForRestrictionRequest)
  })
_sym_db.RegisterMessage(GetEquipmentForRestrictionRequest)

GetTerminalsForNodeRequest = _reflection.GeneratedProtocolMessageType('GetTerminalsForNodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTERMINALSFORNODEREQUEST,
  '__module__' : 'zepben.protobuf.nc.nc_requests_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.nc.GetTerminalsForNodeRequest)
  })
_sym_db.RegisterMessage(GetTerminalsForNodeRequest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.zepben.protobuf.ncP\001\252\002\022Zepben.Protobuf.NC'
  _GETIDENTIFIEDOBJECTSREQUEST._serialized_start=60
  _GETIDENTIFIEDOBJECTSREQUEST._serialized_end=123
  _GETNETWORKHIERARCHYREQUEST._serialized_start=125
  _GETNETWORKHIERARCHYREQUEST._serialized_end=172
  _GETEQUIPMENTFORCONTAINERSREQUEST._serialized_start=174
  _GETEQUIPMENTFORCONTAINERSREQUEST._serialized_end=242
  _GETCURRENTEQUIPMENTFORFEEDERREQUEST._serialized_start=244
  _GETCURRENTEQUIPMENTFORFEEDERREQUEST._serialized_end=314
  _GETEQUIPMENTFORRESTRICTIONREQUEST._serialized_start=316
  _GETEQUIPMENTFORRESTRICTIONREQUEST._serialized_end=384
  _GETTERMINALSFORNODEREQUEST._serialized_start=386
  _GETTERMINALSFORNODEREQUEST._serialized_end=447
# @@protoc_insertion_point(module_scope)
