
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-07T10:35:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9518771db755c1cfb150bc38a93f0d6feb33797",
 "version": "1.0.post0.dev5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
