RETURN_FILTER_STR_FIRST = 'first'
RETURN_FILTER_STR_TOP = 'top'
RETURN_FILTER_STR_LAST = 'last'
RETURN_FILTER_STR_BOTTOM = 'bottom'
RETURN_FILTER_STR_ALL = 'all'
RETURN_TYPE_OPTIONS = {RETURN_FILTER_STR_FIRST, RETURN_FILTER_STR_ALL,
                       RETURN_FILTER_STR_TOP, RETURN_FILTER_STR_BOTTOM,
                       RETURN_FILTER_STR_LAST}

DEFAULT_SIMILARITY_WEIGHT = 0.5