
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-08T19:35:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8063246f8b3eed9f3abc805defd707286c52c403",
 "version": "v0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
