
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "60a667142ecac81ed02208d3b7f6742bf1b9478e",
 "version": "1.0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
