
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-08T09:29:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "82e8ef5a1612e7d5a0b6d770d8530e6ab5493b41",
 "version": "0.7.165"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
