
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-10T16:08:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4d723be0aec0688d536e670c8fabea2d5f9178c",
 "version": "0.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
