
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-05T12:50:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8cd644769bf4fba59cbcb589dc9c87ce6c14a178",
 "version": "0.2.20.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
