
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-06T18:24:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac37d77200519062e4bf7b64f37ee7bd96f20fe4",
 "version": "3.0.0dev11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
