
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-10T18:13:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "95ea526cc98b26b2e86f2614741088395e294bee",
 "version": "0.2.21.post0.dev24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
