
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-11T11:35:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "df7e761f19d23f1dd6357a8ec3bf092a24df4359",
 "version": "0.7.1.post.dev704"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
