
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-04T09:57:13-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "72a6c109a0be162dd8b256ed0f287b4842844294",
 "version": "2.0.0b7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
