# Generated by Django 3.2 on 2022-07-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expiry_addon", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resourceexpirypolicy",
            options={"verbose_name_plural": "Resource Expiry Policies"},
        ),
        migrations.AlterField(
            model_name="resourceexpirypolicy",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
