__version__ = "1.4.3"
__git_commiter_name__ = "Maxim Kigel"
__git_commiter_email__ = "mkigel@infinidat.com"
__git_branch__ = '(detached from v1.4.3)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'a30f9a10dbb2c1ae0fbb85de2256ebfef3134438'
__git_head_subject__ = 'Finished Release v1.4.3'
__git_head_message__ = ''
__git_dirty_diff__ = ''
__git_commit_date__ = '2022-08-09 09:52:37'
