
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-06T11:50:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4782ebdfce9caaeaf4de2438475acf60249bdea",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
