
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-05T13:11:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f1d61890c32e63a53faf2e1700d2c641a5b177c",
 "version": "0.2.20.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
