
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-04T14:04:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad2f3a62afa9a8852bbf0ff3f1df1aadb3b74c8d",
 "version": "0.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
