
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-06T13:47:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd50f36b404d1c89a841907d3682537d5f7719ab",
 "version": "2.7.9.dev20220807"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
