
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-08T09:55:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c48300ca57cbfb1504d57d75d90bfe7a261dc5b",
 "version": "1.12.61"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
