# Generated by Django 3.2.14 on 2022-07-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupToGroupConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='auth.group', verbose_name='Grouper group')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouper_connections', to='auth.group', verbose_name='Source group')),
            ],
            options={
                'verbose_name': 'Group to group connection',
                'verbose_name_plural': 'Group to group connection',
                'unique_together': {('grouper', 'source')},
            },
        ),
    ]
