
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-09T15:39:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7942fe8ba360dff1f57647b74744a714f54325a7",
 "version": "0.2.21.post0.dev12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
