
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-11T11:10:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "05f4c099682d3219e60b39332159546690ec6738",
 "version": "2.1.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
