
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-09T01:15:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "30ea9190a6de3c34bc64ea452117e533fc73f9a9",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
