
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e7d84636d8b56e8a0caaaa871623f3facaf181b0",
 "version": "2.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
