
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-10T16:57:32-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ac306068fe67d94e21f026c1006e0e5ffb32e87",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
