from funcparserlib.lexer import Token
from typing import Iterator

class Statement:
    def compile(self, indent: str = ...) -> str: ...

def lex(data: str) -> Iterator[Token]: ...

def parse(tokens: Iterator[Token]) -> Iterator[Statement]: ...

def compile(statements: Iterator[Statement]) -> Iterator[str]: ...
