
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-11T12:26:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba1670f2ec988945ce83bd6fbbf0848d7ea7479b",
 "version": "2.0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
