# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: support_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ansys.grpc.dpf.support_pb2 as support__pb2
import ansys.grpc.dpf.time_freq_support_pb2 as time__freq__support__pb2
import ansys.grpc.dpf.meshed_region_pb2 as meshed__region__pb2
import ansys.grpc.dpf.cyclic_support_pb2 as cyclic__support__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15support_service.proto\x12 ansys.api.dpf.support_service.v0\x1a\rsupport.proto\x1a\x17time_freq_support.proto\x1a\x13meshed_region.proto\x1a\x14\x63yclic_support.proto\"\x82\x02\n\x0fSupportResponse\x12P\n\x11time_freq_support\x18\x01 \x01(\x0b\x32\x33.ansys.api.dpf.time_freq_support.v0.TimeFreqSupportH\x00\x12\x43\n\x0b\x64omain_mesh\x18\x02 \x01(\x0b\x32,.ansys.api.dpf.meshed_region.v0.MeshedRegionH\x00\x12H\n\x0e\x63yclic_support\x18\x03 \x01(\x0b\x32..ansys.api.dpf.cyclic_support.v0.CyclicSupportH\x00\x42\x0e\n\x0csupport_type2t\n\x0eSupportService\x12\x62\n\nGetSupport\x12!.ansys.api.dpf.support.v0.Support\x1a\x31.ansys.api.dpf.support_service.v0.SupportResponseB\"\xaa\x02\x1f\x41nsys.Api.Dpf.SupportService.v0b\x06proto3')



_SUPPORTRESPONSE = DESCRIPTOR.message_types_by_name['SupportResponse']
SupportResponse = _reflection.GeneratedProtocolMessageType('SupportResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUPPORTRESPONSE,
  '__module__' : 'support_service_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.dpf.support_service.v0.SupportResponse)
  })
_sym_db.RegisterMessage(SupportResponse)

_SUPPORTSERVICE = DESCRIPTOR.services_by_name['SupportService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\037Ansys.Api.Dpf.SupportService.v0'
  _SUPPORTRESPONSE._serialized_start=143
  _SUPPORTRESPONSE._serialized_end=401
  _SUPPORTSERVICE._serialized_start=403
  _SUPPORTSERVICE._serialized_end=519
# @@protoc_insertion_point(module_scope)
