# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_jokes.ipynb.

# %% auto 0
__all__ = ['papagaio']

# %% ../01_jokes.ipynb 3
def papagaio():
    return f"Aprendeu a falar 'Como estamos?' e virou PM." 
