
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-05T17:44:39+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6fa591a7b3f10573a7ecde9bb727ba472bbc253",
 "version": "2.9.56.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
