
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-04T09:01:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4f1e1d55232692cbdd4aec40279568f2798beaa3",
 "version": "0.1.0a67"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
