
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-08T11:09:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdb090e70b1812d0fc17da530e3e8c8e38a9f06b",
 "version": "1.5.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
