
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-04T14:08:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "84bc4ce19e0753799dfb2d974cc274501ecf68b4",
 "version": "2731"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
