
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-06T02:32:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "398c63aa137a429dc212e555959eb607075707bf",
 "version": "v1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
