DEFAULT_PORT = 5001
DEFAULT_HOST = "0.0.0.0"
DEFAULT_WORKER_COUNT = 1
DEFAULT_APPINSIGHTS_ENABLED = "false"
DEFAULT_WORKER_TIMEOUT_SECONDS = "300"


# Environment Variables

ENV_AML_APP_ROOT = "AML_APP_ROOT"
ENV_AZUREML_ENTRY_SCRIPT = "AZUREML_ENTRY_SCRIPT"
ENV_AZUREML_MODEL_DIR = "AZUREML_MODEL_DIR"
ENV_AML_APP_INSIGHTS_ENABLED = "AML_APP_INSIGHTS_ENABLED"
ENV_AML_APP_INSIGHTS_KEY = "AML_APP_INSIGHTS_KEY"
ENV_WORKER_COUNT = "WORKER_COUNT"
ENV_WORKER_TIMEOUT = "WORKER_TIMEOUT"
ENV_WORKER_PRELOAD = "WORKER_PRELOAD"
ENV_PORT = "SERVER_PORT"
