
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-04T11:06:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d75a705bd671b12aa231142bd483ce0be285ea6",
 "version": "2730"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
