
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-05T14:26:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "91d81713ae04c65ac1930dddce221511e1c8d07e",
 "version": "2022.8.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
