# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '1.0.0rc3'
git_version = '04cac00f83d910db31b48b1b182e4619f98ff1e6'
