
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-03T15:12:25+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "e74d80c662ccea7bf62d01df0a877a5985c246e8",
 "version": "0.2.52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
