
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-08T12:12:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b7107de50ff82d489c3fd6bbeaaa09b4ed6c67c",
 "version": "0.9.62"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
