# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_classification.ipynb.

# %% auto 0
__all__ = ['ks']

# %% ../nbs/02_classification.ipynb 3
import numpy as np
import pandas as pd
from numpy import ndarray

def ks(y_proba0: ndarray,  # array of probabilities for class 0
       y_proba1: ndarray): # array of probabilities for class 1
    "Calculate the KS Metrics"

    pass
