
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-07T02:45:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1e166113c53d5854aaa110ee3573036a85593850",
 "version": "0.4.dev2232"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
