# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/speos/file/v1/file_transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+ansys/api/speos/file/v1/file_transfer.proto\x12\x17\x61nsys.api.speos.file.v1\x1a\x1egoogle/protobuf/duration.proto\"\x1f\n\x1dGetServerTmpDirectory_Request\"8\n\x1eGetServerTmpDirectory_Response\x12\x16\n\x0e\x64irectory_path\x18\x01 \x01(\t\"%\n\x05\x43hunk\x12\x0e\n\x06\x62inary\x18\x01 \x01(\x0c\x12\x0c\n\x04size\x18\x02 \x01(\x03\"\x84\x01\n\x13\x46ileUpload_Response\x12\x13\n\x0b\x63hunk_count\x18\x01 \x01(\x03\x12\x32\n\x0fupload_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x11\n\tfile_size\x18\x03 \x01(\x03\x12\x11\n\tfile_path\x18\x04 \x01(\t2\xfe\x01\n\x13\x46ileTransferService\x12\x88\x01\n\x15GetServerTmpDirectory\x12\x36.ansys.api.speos.file.v1.GetServerTmpDirectory_Request\x1a\x37.ansys.api.speos.file.v1.GetServerTmpDirectory_Response\x12\\\n\nFileUpload\x12\x1e.ansys.api.speos.file.v1.Chunk\x1a,.ansys.api.speos.file.v1.FileUpload_Response(\x01\x62\x06proto3')



_GETSERVERTMPDIRECTORY_REQUEST = DESCRIPTOR.message_types_by_name['GetServerTmpDirectory_Request']
_GETSERVERTMPDIRECTORY_RESPONSE = DESCRIPTOR.message_types_by_name['GetServerTmpDirectory_Response']
_CHUNK = DESCRIPTOR.message_types_by_name['Chunk']
_FILEUPLOAD_RESPONSE = DESCRIPTOR.message_types_by_name['FileUpload_Response']
GetServerTmpDirectory_Request = _reflection.GeneratedProtocolMessageType('GetServerTmpDirectory_Request', (_message.Message,), {
  'DESCRIPTOR' : _GETSERVERTMPDIRECTORY_REQUEST,
  '__module__' : 'ansys.api.speos.file.v1.file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.speos.file.v1.GetServerTmpDirectory_Request)
  })
_sym_db.RegisterMessage(GetServerTmpDirectory_Request)

GetServerTmpDirectory_Response = _reflection.GeneratedProtocolMessageType('GetServerTmpDirectory_Response', (_message.Message,), {
  'DESCRIPTOR' : _GETSERVERTMPDIRECTORY_RESPONSE,
  '__module__' : 'ansys.api.speos.file.v1.file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.speos.file.v1.GetServerTmpDirectory_Response)
  })
_sym_db.RegisterMessage(GetServerTmpDirectory_Response)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'ansys.api.speos.file.v1.file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.speos.file.v1.Chunk)
  })
_sym_db.RegisterMessage(Chunk)

FileUpload_Response = _reflection.GeneratedProtocolMessageType('FileUpload_Response', (_message.Message,), {
  'DESCRIPTOR' : _FILEUPLOAD_RESPONSE,
  '__module__' : 'ansys.api.speos.file.v1.file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.speos.file.v1.FileUpload_Response)
  })
_sym_db.RegisterMessage(FileUpload_Response)

_FILETRANSFERSERVICE = DESCRIPTOR.services_by_name['FileTransferService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETSERVERTMPDIRECTORY_REQUEST._serialized_start=104
  _GETSERVERTMPDIRECTORY_REQUEST._serialized_end=135
  _GETSERVERTMPDIRECTORY_RESPONSE._serialized_start=137
  _GETSERVERTMPDIRECTORY_RESPONSE._serialized_end=193
  _CHUNK._serialized_start=195
  _CHUNK._serialized_end=232
  _FILEUPLOAD_RESPONSE._serialized_start=235
  _FILEUPLOAD_RESPONSE._serialized_end=367
  _FILETRANSFERSERVICE._serialized_start=370
  _FILETRANSFERSERVICE._serialized_end=624
# @@protoc_insertion_point(module_scope)
