# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.speos.file.v1 import file_transfer_pb2 as ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2


class FileTransferServiceStub(object):
    """service to transfer a file
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerTmpDirectory = channel.unary_unary(
                '/ansys.api.speos.file.v1.FileTransferService/GetServerTmpDirectory',
                request_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.GetServerTmpDirectory_Request.SerializeToString,
                response_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.GetServerTmpDirectory_Response.FromString,
                )
        self.FileUpload = channel.stream_unary(
                '/ansys.api.speos.file.v1.FileTransferService/FileUpload',
                request_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Chunk.SerializeToString,
                response_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.FileUpload_Response.FromString,
                )


class FileTransferServiceServicer(object):
    """service to transfer a file
    """

    def GetServerTmpDirectory(self, request, context):
        """Get the path of the directory on the server where the files are uploaded
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileUpload(self, request_iterator, context):
        """Upload a file on the server - precise the file name in metadata with the "file_name" key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileTransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerTmpDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerTmpDirectory,
                    request_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.GetServerTmpDirectory_Request.FromString,
                    response_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.GetServerTmpDirectory_Response.SerializeToString,
            ),
            'FileUpload': grpc.stream_unary_rpc_method_handler(
                    servicer.FileUpload,
                    request_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Chunk.FromString,
                    response_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.FileUpload_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.speos.file.v1.FileTransferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileTransferService(object):
    """service to transfer a file
    """

    @staticmethod
    def GetServerTmpDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.speos.file.v1.FileTransferService/GetServerTmpDirectory',
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.GetServerTmpDirectory_Request.SerializeToString,
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.GetServerTmpDirectory_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileUpload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ansys.api.speos.file.v1.FileTransferService/FileUpload',
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Chunk.SerializeToString,
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.FileUpload_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
