
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-04T13:48:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ad48259f1d5fc92397a2567e72c829984674fb1",
 "version": "0.15.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
