
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-05T19:11:00-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8539b17c97082cf554711044cc66653f1d8e9da",
 "version": "2.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
