#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['fbchat', 'fbchat._events', 'fbchat._models', 'fbchat._threads']

package_data = \
{'': ['*']}

install_requires = \
['attrs>=19.1', 'beautifulsoup4~=4.0', 'aiohttp', 'yarl', 'paho-mqtt~=1.5']

extras_require = \
{'doc': ['sphinx'],
 'lint': ['black', 'pyright'],
 'proxy': ['aiohttp-socks', 'pysocks'],
 'test': ['pytest>=4.3,<6.0']}

setup(name='fbchat-asyncio-kvgx12',
      version='0.6.24',
      description='Facebook Messenger for Python.',
      author=None,
      author_email='kvgx12 <szczepan7700@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.9',
     )
