# Generated by Django 3.2 on 2022-07-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lockable_resource", "0008_lockableresource_locked_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceExpiryPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("expiry_hour", models.IntegerField(default=0)),
                (
                    "lockable_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lockable_resource.lockableresource",
                    ),
                ),
            ],
        ),
    ]
