# Generated by Django 3.2 on 2022-07-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expiry_addon", "0002_auto_20220711_1038"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceexpirypolicy",
            name="current_expiry_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
