
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-08T10:01:24+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "6646252255f9adcf6ae1df555a0f6d27693c1903",
 "version": "v2.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
