# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_io_control.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edge_core.datatypes.io_common_pb2 as io__common__pb2
import edge_core.datatypes.io_property_pb2 as io__property__pb2

from edge_core.datatypes.io_common_pb2 import *
from edge_core.datatypes.io_property_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18service_io_control.proto\x12\x05io.v2\x1a\x0fio_common.proto\x1a\x11io_property.proto\"\xd2\x01\n\x10IoControlRequest\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.io.v2.MessageHeader\x12\x0f\n\x07\x65\x64ge_id\x18\x02 \x01(\t\x12\x16\n\x0e\x64\x61ta_source_id\x18\x03 \x01(\t\x12\x13\n\x0b\x63\x61ller_name\x18\x04 \x01(\t\x12\x0f\n\x07io_name\x18\x05 \x01(\t\x12&\n\x0bmethod_type\x18\x06 \x01(\x0e\x32\x11.io.v2.MethodType\x12!\n\tset_value\x18\x07 \x01(\x0b\x32\x0e.io.v2.IoValue\"\x8d\x02\n\x11IoControlResponse\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.io.v2.MessageHeader\x12\x0f\n\x07\x65\x64ge_id\x18\x02 \x01(\t\x12\x16\n\x0e\x64\x61ta_source_id\x18\x03 \x01(\t\x12\x13\n\x0b\x63\x61ller_name\x18\x04 \x01(\t\x12\x0f\n\x07io_name\x18\x05 \x01(\t\x12&\n\x0bmethod_type\x18\x06 \x01(\x0e\x32\x11.io.v2.MethodType\x12\x11\n\ttimestamp\x18\x07 \x01(\x04\x12!\n\tget_value\x18\x08 \x01(\x0b\x32\x0e.io.v2.IoValue\x12%\n\x06result\x18\t \x01(\x0b\x32\x15.io.v2.ResponseResult\"\xa6\x01\n\x0eIoListResponse\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.io.v2.MessageHeader\x12\x1e\n\x03ios\x18\x02 \x03(\x0b\x32\x11.io.v2.IoProperty\x12\'\n\tio_values\x18\x03 \x03(\x0b\x32\x14.io.v2.SingleIoValue\x12%\n\x06result\x18\x04 \x01(\x0b\x32\x15.io.v2.ResponseResult2\x8e\x01\n\x10IoControlService\x12\x46\n\x0fSingleIoControl\x12\x17.io.v2.IoControlRequest\x1a\x18.io.v2.IoControlResponse\"\x00\x12\x32\n\tGetIoList\x12\x0c.io.v2.Empty\x1a\x15.io.v2.IoListResponse\"\x00P\x00P\x01\x62\x06proto3')



_IOCONTROLREQUEST = DESCRIPTOR.message_types_by_name['IoControlRequest']
_IOCONTROLRESPONSE = DESCRIPTOR.message_types_by_name['IoControlResponse']
_IOLISTRESPONSE = DESCRIPTOR.message_types_by_name['IoListResponse']
IoControlRequest = _reflection.GeneratedProtocolMessageType('IoControlRequest', (_message.Message,), {
  'DESCRIPTOR' : _IOCONTROLREQUEST,
  '__module__' : 'service_io_control_pb2'
  # @@protoc_insertion_point(class_scope:io.v2.IoControlRequest)
  })
_sym_db.RegisterMessage(IoControlRequest)

IoControlResponse = _reflection.GeneratedProtocolMessageType('IoControlResponse', (_message.Message,), {
  'DESCRIPTOR' : _IOCONTROLRESPONSE,
  '__module__' : 'service_io_control_pb2'
  # @@protoc_insertion_point(class_scope:io.v2.IoControlResponse)
  })
_sym_db.RegisterMessage(IoControlResponse)

IoListResponse = _reflection.GeneratedProtocolMessageType('IoListResponse', (_message.Message,), {
  'DESCRIPTOR' : _IOLISTRESPONSE,
  '__module__' : 'service_io_control_pb2'
  # @@protoc_insertion_point(class_scope:io.v2.IoListResponse)
  })
_sym_db.RegisterMessage(IoListResponse)

_IOCONTROLSERVICE = DESCRIPTOR.services_by_name['IoControlService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IOCONTROLREQUEST._serialized_start=72
  _IOCONTROLREQUEST._serialized_end=282
  _IOCONTROLRESPONSE._serialized_start=285
  _IOCONTROLRESPONSE._serialized_end=554
  _IOLISTRESPONSE._serialized_start=557
  _IOLISTRESPONSE._serialized_end=723
  _IOCONTROLSERVICE._serialized_start=726
  _IOCONTROLSERVICE._serialized_end=868
# @@protoc_insertion_point(module_scope)
