# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sinker_payload.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import edge_core.datatypes.data_source_property_pb2 as data__source__property__pb2
try:
  io__property__pb2 = data__source__property__pb2.io__property__pb2
except AttributeError:
  io__property__pb2 = data__source__property__pb2.io_property_pb2
import edge_core.datatypes.io_common_pb2 as io__common__pb2
import edge_core.datatypes.io_property_pb2 as io__property__pb2

from edge_core.datatypes.data_source_property_pb2 import *
from edge_core.datatypes.io_common_pb2 import *
from edge_core.datatypes.io_property_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sinker_payload.proto\x12\x05io.v2\x1a\x1a\x64\x61ta_source_property.proto\x1a\x0fio_common.proto\x1a\x11io_property.proto\"\xac\x01\n\x11IoRequestToSinker\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.io.v2.MessageHeader\x12&\n\x0bmethod_type\x18\x02 \x01(\x0e\x32\x11.io.v2.MethodType\x12&\n\x0bio_property\x18\x03 \x01(\x0b\x32\x11.io.v2.IoProperty\x12!\n\tset_value\x18\x04 \x01(\x0b\x32\x0e.io.v2.IoValue\"}\n\x08NestedIo\x12&\n\x0bio_property\x18\x01 \x01(\x0b\x32\x11.io.v2.IoProperty\x12&\n\x0bmethod_type\x18\x02 \x01(\x0e\x32\x11.io.v2.MethodType\x12!\n\tset_value\x18\x03 \x01(\x0b\x32\x0e.io.v2.IoValue\"\x90\x01\n\x14\x42\x61tchRequestToSinker\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.io.v2.MessageHeader\x12.\n\x0b\x64\x61ta_source\x18\x02 \x01(\x0b\x32\x19.io.v2.DataSourceProperty\x12\"\n\tnested_io\x18\x03 \x03(\x0b\x32\x0f.io.v2.NestedIo\"\xe0\x01\n\x11ResponseIoDataset\x12\x0f\n\x07io_name\x18\x01 \x01(\t\x12(\n\x0c\x64\x61taset_type\x18\x02 \x01(\x0e\x32\x12.io.v2.DatasetType\x12\"\n\tdata_type\x18\x03 \x01(\x0e\x32\x0f.io.v2.DataType\x12\x10\n\x08recoding\x18\x04 \x01(\x08\x12-\n\x0fsingle_io_value\x18\x05 \x01(\x0b\x32\x14.io.v2.SingleIoValue\x12+\n\x0emulti_io_value\x18\x06 \x01(\x0b\x32\x13.io.v2.MultiIoValue\"\x92\x01\n\x12ResponseFromSinker\x12\x0f\n\x07\x65\x64ge_id\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x61ta_source_id\x18\x02 \x01(\t\x12,\n\nio_dataset\x18\x03 \x03(\x0b\x32\x18.io.v2.ResponseIoDataset\x12%\n\x06result\x18\x04 \x01(\x0b\x32\x15.io.v2.ResponseResultP\x00P\x01P\x02\x62\x06proto3')



_IOREQUESTTOSINKER = DESCRIPTOR.message_types_by_name['IoRequestToSinker']
_NESTEDIO = DESCRIPTOR.message_types_by_name['NestedIo']
_BATCHREQUESTTOSINKER = DESCRIPTOR.message_types_by_name['BatchRequestToSinker']
_RESPONSEIODATASET = DESCRIPTOR.message_types_by_name['ResponseIoDataset']
_RESPONSEFROMSINKER = DESCRIPTOR.message_types_by_name['ResponseFromSinker']
IoRequestToSinker = _reflection.GeneratedProtocolMessageType('IoRequestToSinker', (_message.Message,), {
  'DESCRIPTOR' : _IOREQUESTTOSINKER,
  '__module__' : 'sinker_payload_pb2'
  # @@protoc_insertion_point(class_scope:io.v2.IoRequestToSinker)
  })
_sym_db.RegisterMessage(IoRequestToSinker)

NestedIo = _reflection.GeneratedProtocolMessageType('NestedIo', (_message.Message,), {
  'DESCRIPTOR' : _NESTEDIO,
  '__module__' : 'sinker_payload_pb2'
  # @@protoc_insertion_point(class_scope:io.v2.NestedIo)
  })
_sym_db.RegisterMessage(NestedIo)

BatchRequestToSinker = _reflection.GeneratedProtocolMessageType('BatchRequestToSinker', (_message.Message,), {
  'DESCRIPTOR' : _BATCHREQUESTTOSINKER,
  '__module__' : 'sinker_payload_pb2'
  # @@protoc_insertion_point(class_scope:io.v2.BatchRequestToSinker)
  })
_sym_db.RegisterMessage(BatchRequestToSinker)

ResponseIoDataset = _reflection.GeneratedProtocolMessageType('ResponseIoDataset', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEIODATASET,
  '__module__' : 'sinker_payload_pb2'
  # @@protoc_insertion_point(class_scope:io.v2.ResponseIoDataset)
  })
_sym_db.RegisterMessage(ResponseIoDataset)

ResponseFromSinker = _reflection.GeneratedProtocolMessageType('ResponseFromSinker', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEFROMSINKER,
  '__module__' : 'sinker_payload_pb2'
  # @@protoc_insertion_point(class_scope:io.v2.ResponseFromSinker)
  })
_sym_db.RegisterMessage(ResponseFromSinker)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IOREQUESTTOSINKER._serialized_start=96
  _IOREQUESTTOSINKER._serialized_end=268
  _NESTEDIO._serialized_start=270
  _NESTEDIO._serialized_end=395
  _BATCHREQUESTTOSINKER._serialized_start=398
  _BATCHREQUESTTOSINKER._serialized_end=542
  _RESPONSEIODATASET._serialized_start=545
  _RESPONSEIODATASET._serialized_end=769
  _RESPONSEFROMSINKER._serialized_start=772
  _RESPONSEFROMSINKER._serialized_end=918
# @@protoc_insertion_point(module_scope)
