
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-09T18:30:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f69f1f4f40ffb60c214d759e2da35435ccb0919",
 "version": "0.2.21.post0.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
