
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-05T17:04:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "12cc72ad7bd4bcd813e96163501b4b7589332a64",
 "version": "0.1.0a68"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
