
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-10T13:19:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "39db6fb16d4131844f0e25010aac58ccd2af4780",
 "version": "2.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
