
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-05T18:46:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a04acc5e774d7ca30548d6f30207960243d9769c",
 "version": "0.2.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
