
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-04T15:22:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "acab54b7c52add5a893007379195fc0722f12da1",
 "version": "2732"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
