
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-05T18:53:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9173b2014b8412f557fec4de0df9a00866084d58",
 "version": "0.2.21.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
