
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-05T15:28:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0c9aa4c18a93b6b8ba1cb7c900e5ce5e5396da6b",
 "version": "1.19.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
