
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-11T12:07:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7b8ef3e85828cfd5ffc0d6d0cbbfc4279c669d37",
 "version": "1.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
