
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-07T23:14:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "46f782c86a7fb65e28d9ea2fc70bee7fc8692ba1",
 "version": "v0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
