
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-29T15:11:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "29e934dd1031d33edd7664785c254359bd6ce802",
 "version": "0.10.0b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
