
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-11T15:23:04+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "42104d4702cb697b655a4edfedbbb1942f59cfdd",
 "version": "3.8.13.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
