
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-20T10:50:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea1ddf46beacf292041309c9b2e0ef179ddd9153",
 "version": "0.3.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
