# Generated by Django 4.0.6 on 2022-08-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_static', '0002_throttling'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statictoken',
            table=None,
        ),
    ]
