
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-10T14:26:46-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "df92d424ce1a7b72e064e84d3179d4f8f03ee433",
 "version": "0.0.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
