#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
This file was generated by Alchemist - Automated build system based on Buildbot.
It is intended for propagation of build information back to the original project.
"""

__bauthor__ = "Alchemist - Automated build system based on Buildbot"
__brevision__ = "fb9b8d36449e137a0d3ff9c69100e3f978f60981"
__bcodename__ = "production"
__bsuite__ = "stable"
__bversion__ = "2.10.0.284"
__bversion_full__ = "2.10.0.284-fb9b8d36449e137a0d3ff9c69100e3f978f60981 (production-stable)"
__bdate__ = "2022-07-20T12:38:05.161575"