# Generated by Django 4.0.6 on 2022-07-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor', '0007_auto_20201201_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedevice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
