
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-11T16:00:25+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "65d68858fcae30ba43602d63103abcabca387f97",
 "version": "1.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
