
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-11T14:11:44+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c223eb6decbc7c6a3497bdaba1a8f6cdd0ebccd2",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
