
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-08T17:42:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9bd17883f9bec5ed2420c83813f963c37adf631",
 "version": "0.2.21.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
