
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-07T12:21:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e9c8c03da23894ef721a7a2ed36c127e8023b29",
 "version": "1.0.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
