
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-09T14:34:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c322e0500037cf1a6a1bdfb00c8dd8b2b4e3992",
 "version": "0.16.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
